### ISSUE TITLE
TypeError: '>' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by mybearworld** [Chiroyce1/scratch-user-data#7]
I get this error when running this:

```
Traceback (most recent call last):
  File "C:\path\to\main.py", line 140, in <module>
    main()
  File "C:\path\to\main.py", line 131, in main
    check_for_updates()
  File "C:\path\to\main.py", line 52, in check_for_updates
    if current_version > latest_version:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'float' and 'str'
```

**Comment by Chiroyce1** [comment]
Thank you for reporting this issue, resolved in https://github.com/Chiroyce1/scratch-user-info/commit/089acdf42a18cd25a964764693af9d75d6e54d07.
